package com.vic.crm.enums;

/**
 * Sub-status across all stages.
 */
public enum CandidateSubStatus {
    SOURCED,
    CONTACTED,
    SCREENING_SCHEDULED,
    SCREENING_PASSED,
    SCREENING_FAILED,
    TRAINING_CONTRACT_SENT,
    TRAINING_CONTRACT_SIGNED,
    BATCH_ASSIGNED,
    DIRECT_MARKETING_READY,

    IN_TRAINING,
    RESUME_PREPARING,
    RESUME_READY,
    MOCK_THEORY_READY,
    MOCK_THEORY_SCHEDULED,
    MOCK_THEORY_PASSED,
    MOCK_THEORY_FAILED,
    MOCK_REAL_SCHEDULED,
    MOCK_REAL_PASSED,
    MOCK_REAL_FAILED,

    MARKETING_ACTIVE,

    OFFER_PENDING,
    OFFER_ACCEPTED,
    OFFER_DECLINED,

    WAITING_DOCS,
    PERSONAL_PAUSE,
    VISA_ISSUE,
    OTHER,

    PLACED_CONFIRMED,
    CLOSED,
    SELF_WITHDRAWN
}
