package com.vic.crm.enums;

/**
 * Sub-status across all stages.
 */
public enum CandidateSubStatus {
    SOURCED,
    CONTACTED,
    SCREENING_SCHEDULED,
    SCREENING_PASSED,
    SCREENING_FAILED,
    DIRECT_MARKETING_READY,

    IN_TRAINING,
    HOMEWORK_PENDING,
    MOCK_IN_PROGRESS,
    TRAINING_COMPLETED,

    RESUME_READY,
    PROFILE_PACKAGED,
    VENDOR_OUTREACH,
    SUBMITTED,

    VENDOR_SCREEN,
    CLIENT_ROUND_1,
    CLIENT_ROUND_2,
    CLIENT_ROUND_3_PLUS,

    OFFER_PENDING,
    OFFER_ACCEPTED,
    OFFER_DECLINED,

    WAITING_DOCS,
    PERSONAL_PAUSE,
    VISA_ISSUE,
    OTHER,

    PLACED_CONFIRMED,
    CLOSED,
    SELF_WITHDRAWN
}
